version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres
    environment:
      - ALLOW_ORIGINS
      - OPENAI_API_KEY
      - MODEL
      - EMBEDDING_MODEL
      - EMBEDDING_DIMENSIONS
      - REDIS_HOST=redis
      - REDIS_PORT
      - DOCS_DIR
      - EXPORT_DIR
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@postgres:5432/tai_relational_db

  redis:
    image: redis/redis-stack-server:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_ARGS=--save 600 1 --save 300 10 --save 60 100

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_DB=tai_relational_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
volumes:
  redis_data:
  postgres_data: