"""changed type of message-role to string

Revision ID: fdf8741bf7a1
Revises: efe30d08d356
Create Date: 2025-06-15 19:44:28.413146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fdf8741bf7a1'
down_revision: Union[str, None] = 'efe30d08d356'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agents', 'config',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('messages', 'role',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'role',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('agents', 'config',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
