from typing import Protocol
from app.models import Agent


class AgentRepositoryInterface(Protocol):
    async def exists(self) -> bool: ...
    async def get_by_name(self, name: str) -> Agent | None: ...
    async def get_by_model(self, model: str) -> Agent | None: ...